binlog:
 delimiter: \n #for next version
 directory: binlogs/
 oversize: 1048576 #1mb
 every_check_oversize: y 
 chance_check_oversize: 1 #from 1000
snapshot:
 delimiter: \n #for next version
 directory: snapshots/
